export const currencies = [
  { label: 'TRY', value: 'Türk Lirası' },
  { label: 'USD', value: 'Amerikan Doları' },
  { label: 'EUR', value: 'Euro' },
  { label: 'GBP', value: 'İngiliz Poundu' },
  { label: 'JPY', value: 'Japon Yeni' },
  { label: 'RUB', value: 'Rus Rublesi' },
  { label: 'CHF', value: 'İsviçre Frangı' },
  { label: 'AUD', value: 'Avustralya Doları' },
  { label: 'CAD', value: 'Kanada Doları' },
  { label: 'SGD', value: 'Singapur Doları' },
  { label: 'KRW', value: 'Güney Kore Wonu' },
  { label: 'AZN', value: 'Azerbaycan Manatı' },
  { label: 'BGN', value: 'Bulgar Levası' },
  { label: 'THB', value: 'Tayland Bahtı' },
  { label: 'PLN', value: 'Polonya Zlotisi' },
  { label: 'NOK', value: 'Norveç Kronu' },
  { label: 'IDR', value: 'Endonezya Rupisi' },
  { label: 'KGS', value: 'Kırgızistan Somu' },
];
